### ISSUE TITLE
Bug Report Device is not of type httpgd

### ISSUE THREAD

**Issue by JiaxiangBU** [nx10/httpgd#27] opened 2020-06-24 09:39 UTC
``` r
httpgd::httpgd()
#> httpgd live server running at:
#>   http://127.0.0.1:64029/live?token=iyrJrYxw
```

<sup>Created on 2020-06-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                              
#>  version  R version 3.6.0 (2019-04-26)                       
#>  os       Windows 7 x64 SP 1                                 
#>  system   x86_64, mingw32                                    
#>  ui       RTerm                                              
#>  language (EN)                                               
#>  collate  Chinese (Simplified)_People's Republic of China.936
#>  ctype    Chinese (Simplified)_People's Republic of China.936
#>  tz       Asia/Taipei                                        
#>  date     2020-06-24                                         
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.2)                
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                
#>  callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)                
#>  cli           2.0.1      2020-01-08 [1] CRAN (R 3.6.2)                
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                
#>  devtools      2.1.0      2019-07-06 [1] CRAN (R 3.6.1)                
#>  digest        0.6.19     2019-05-20 [1] CRAN (R 3.6.0)                
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                
#>  fansi         0.4.0      2018-10-05 [1] CRAN (R 3.6.0)                
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                
#>  httpgd        0.4.0      2020-06-24 [1] local                         
#>  knitr         1.27       2020-01-16 [1] CRAN (R 3.6.2)                
#>  later         1.0.0      2019-10-04 [1] CRAN (R 3.6.1)                
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)                
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.1)                
#>  pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.1)                
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.1)                
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.6.0)                
#>  processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)                
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.2)                
#>  Rcpp          1.0.4.6    2020-04-09 [1] CRAN (R 3.6.3)                
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.1)                
#>  rlang         0.4.4      2020-01-28 [1] CRAN (R 3.6.0)                
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)                
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                
#>  systemfonts   0.2.3      2020-06-09 [1] CRAN (R 3.6.3)                
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                
#>  usethis       1.5.1.9000 2020-02-04 [1] Github (r-lib/usethis@e7c1f17)
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                
#>  xfun          0.8        2019-06-25 [1] CRAN (R 3.6.1)                
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                
#> 
#> [1] C:/Program Files/R/R-3.6.0/library
```

</details>

When I run `httpgd::httpgdBrowse()` to open the URL, I get this error.

```r
Error in httpgdState(which) : Device is not of type httpgd
5.
stop("Device is not of type httpgd")
4.
httpgdState(which)
3.
httpgdURL(endpoint, which)
2.
browseURL(httpgdURL(endpoint, which))
1.
httpgd::httpgdBrowse()

```

**Comment by renkun-ken** [comment] 2020-06-24 09:50
Can't reproduce this. Would you like to try the following and see what `dev.cur()` returns?

```
> httpgd::httpgd()                                                                                                                                                                                                           
httpgd live server running at:
  http://127.0.0.1:41089/live?token=yv2XUrpr

> dev.cur()                                                                                                                                                                                                                  
httpgd 
     2 
```

**Comment by JiaxiangBU** [comment] 2020-06-24 10:18
@renkun-ken Thanks for your reply. I got the status 2, but cannot open this url.

```r
> httpgd::httpgd()   
httpgd live server running at:
  http://127.0.0.1:53577/live?token=1xf8ieaW
> dev.cur() 
httpgd 
     2 
> x = seq(0, 3 * pi, by = 0.1)
> plot(x, sin(x), type = "l")
Server closing... 
```

**Comment by renkun-ken** [comment] 2020-06-24 10:48
Are you using httpgd on your local machine? It looks like your browser are behind some proxy server. Are you using a global proxy?

**Comment by nx10** [comment] 2020-06-24 10:59
In addition: Can you send the output of `R.version`?

**Comment by renkun-ken** [comment] 2020-06-24 11:07
@nx10

@JiaxiangBU's session info expanded:

```
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                              
#>  version  R version 3.6.0 (2019-04-26)                       
#>  os       Windows 7 x64 SP 1                                 
#>  system   x86_64, mingw32                                    
#>  ui       RTerm                                              
#>  language (EN)                                               
#>  collate  Chinese (Simplified)_People's Republic of China.936
#>  ctype    Chinese (Simplified)_People's Republic of China.936
#>  tz       Asia/Taipei                                        
#>  date     2020-06-24                                         
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.2)                
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                
#>  callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)                
#>  cli           2.0.1      2020-01-08 [1] CRAN (R 3.6.2)                
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                
#>  devtools      2.1.0      2019-07-06 [1] CRAN (R 3.6.1)                
#>  digest        0.6.19     2019-05-20 [1] CRAN (R 3.6.0)                
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                
#>  fansi         0.4.0      2018-10-05 [1] CRAN (R 3.6.0)                
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                
#>  httpgd        0.4.0      2020-06-24 [1] local                         
#>  knitr         1.27       2020-01-16 [1] CRAN (R 3.6.2)                
#>  later         1.0.0      2019-10-04 [1] CRAN (R 3.6.1)                
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)                
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.1)                
#>  pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.1)                
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.1)                
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.6.0)                
#>  processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)                
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.2)                
#>  Rcpp          1.0.4.6    2020-04-09 [1] CRAN (R 3.6.3)                
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.1)                
#>  rlang         0.4.4      2020-01-28 [1] CRAN (R 3.6.0)                
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)                
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                
#>  systemfonts   0.2.3      2020-06-09 [1] CRAN (R 3.6.3)                
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                
#>  usethis       1.5.1.9000 2020-02-04 [1] Github (r-lib/usethis@e7c1f17)
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                
#>  xfun          0.8        2019-06-25 [1] CRAN (R 3.6.1)                
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                
#> 
#> [1] C:/Program Files/R/R-3.6.0/library
```

**Comment by JiaxiangBU** [comment] 2020-06-24 12:19
> Are you using httpgd on your local machine? It looks like your browser are behind some proxy server. Are you using a global proxy?

Yes, it runs on a local machine, and I do not set proxy servers before,  it runs by default. @renkun-ken

**Comment by nx10** [comment] 2020-06-24 22:44
I can not reproduce.
Try updating the `later` package. If that does not work try updating R itself to a newer version.
Please let us know if that fixes your issue.

We should consider adding older versions of R to the CI.

**Comment by JiaxiangBU** [comment] 2020-06-28 05:20
@nx10 I update the `later` package.

```r
> install.packages("later")
试开URL’https://cran.rstudio.com/bin/windows/contrib/3.6/later_1.1.0.1.zip'
Content type 'application/zip' length 687638 bytes (671 KB)
downloaded 671 KB

package ‘later’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\lijiaxiang\AppData\Local\Temp\Rtmpo9LBIZ\downloaded_packages
```

``` r
httpgd::httpgd()
#> httpgd live server running at:
#>   http://127.0.0.1:55380/live?token=c8Faxnug
```

<sup>Created on 2020-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                              
#>  version  R version 3.6.0 (2019-04-26)                       
#>  os       Windows 7 x64 SP 1                                 
#>  system   x86_64, mingw32                                    
#>  ui       RTerm                                              
#>  language (EN)                                               
#>  collate  Chinese (Simplified)_People's Republic of China.936
#>  ctype    Chinese (Simplified)_People's Republic of China.936
#>  tz       Asia/Taipei                                        
#>  date     2020-06-28                                         
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.2)                
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                
#>  callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)                
#>  cli           2.0.1      2020-01-08 [1] CRAN (R 3.6.2)                
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                
#>  devtools      2.1.0      2019-07-06 [1] CRAN (R 3.6.1)                
#>  digest        0.6.19     2019-05-20 [1] CRAN (R 3.6.0)                
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                
#>  fansi         0.4.0      2018-10-05 [1] CRAN (R 3.6.0)                
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                
#>  httpgd        0.4.0      2020-06-24 [1] local                         
#>  knitr         1.27       2020-01-16 [1] CRAN (R 3.6.2)                
#>  later         1.1.0.1    2020-06-05 [1] CRAN (R 3.6.3)                
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)                
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.1)                
#>  pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.1)                
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.1)                
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.6.0)                
#>  processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)                
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.2)                
#>  Rcpp          1.0.4.6    2020-04-09 [1] CRAN (R 3.6.3)                
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.1)                
#>  rlang         0.4.4      2020-01-28 [1] CRAN (R 3.6.0)                
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)                
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                
#>  systemfonts   0.2.3      2020-06-09 [1] CRAN (R 3.6.3)                
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                
#>  usethis       1.5.1.9000 2020-02-04 [1] Github (r-lib/usethis@e7c1f17)
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                
#>  xfun          0.8        2019-06-25 [1] CRAN (R 3.6.1)                
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                
#> 
#> [1] C:/Program Files/R/R-3.6.0/library
```

</details>

And I get the same error.

```r
> httpgd::httpgdBrowse()
Error in httpgdState(which) : Device is not of type httpgd
```

I will try a new version of R.

**Comment by JiaxiangBU** [comment] 2020-06-29 07:38
@nx10 this error happens again even I update R to 4.0.2 and later to the latest version.

```r
> httpgd::httpgd()
httpgd live server running at:
  http://127.0.0.1:56677/live?token=lAz6vZzZ
> httpgd::httpgdBrowse()
Server closing... Closed.
> httpgd::httpgdBrowse()
Error in httpgdState(which) : Device is not of type httpgd
```

```r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] later_1.1.0.1

loaded via a namespace (and not attached):
 [1] compiler_4.0.2   assertthat_0.2.1 cli_2.0.2        tools_4.0.2      glue_1.4.1       rstudioapi_0.11 
 [7] Rcpp_1.0.4.6     crayon_1.3.4     fansi_0.4.1      knitr_1.29       xfun_0.15        rlang_0.4.6   
```

**Comment by nx10** [comment] 2020-06-29 15:27
Seems like the server is shutting down after you call `httpgd::httpgdBrowse()` and connect with the browser.
It is very hard to figure out why because I can not reproduce it.
However I am currently working on rewriting most of the server code because we will use another http backend library soon, which might solve your problem.
I will let you know when it is finished so you can try if that solves it. Thank you for testing.

**Comment by JiaxiangBU** [comment] 2020-06-29 15:39
Thanks, forward to the new verison of this package.
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Florian Rupprecht"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 晚上11:28
收件人:&nbsp;"nx10/httpgd"<httpgd@noreply.github.com&gt;;
抄送:&nbsp;"李家翔"<alex.lijiaxiang@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nx10/httpgd] Bug Report Device is not of type httpgd (#27)





 
Seems like the server is shutting down after you call httpgd::httpgdBrowse() and connect with the browser.
 It is very hard to figure out why because I can not reproduce it.
 However I am currently working on rewriting most of the server code because we will use another http backend library soon, which might solve your problem.
 I will let you know when it is finished so you can try if that solves it. Thank you for testing.

**Comment by nx10** [comment] 2020-09-14 13:00
The new version is out. You might want to test again now.

**Comment by nx10** [comment] 2020-09-16 09:26
Closing for now because we can't reproduce it. It would be great if you get to test it sometime and let us know if its working for you.

**Closed by nx10** 2020-09-16 09:26 UTC
Labels: bug
