### ISSUE TITLE
Toolbar not working in VSCode webview

### ISSUE THREAD

**Issue by renkun-ken** [nx10/httpgd#1] opened 2020-05-29 03:34 UTC
In VSCode with vscode-R and session watcher enabled, I use the following code to view the graphics presented by httpgd:

```r
httpgd::httpgd()
getOption("browser")("http://localhost:8288/live")

plot(rnorm(100), main = "title")
abline(h = 0, col = "red")
```

The grahpics looks nice but the toolbar does not seem to work. Whenever I click any button the toolbar disappears and nothing happens.

![image](https://user-images.githubusercontent.com/4662568/83218164-0fcaa700-a1a0-11ea-9664-e6f9db04ec14.png)

**Comment by nx10** [comment] 2020-05-29 15:03
This might be related to the issue with key events not being forwarded to the webview/iframe.
Is it resizing correctly when changing the width or height of the webview? I noticed the scrollbar on the right of your screenshot.

**Comment by renkun-ken** [comment] 2020-05-29 15:53
In VSCode WebView, the resizing works as expected as I change the width or height, but I'm not sure why the scrollbar appears.

**Comment by renkun-ken** [comment] 2020-05-30 23:31
With the latest commit, the toolbar works now but it is hard to click to make it work.

The first click always does not work. I need to put cursor on a button, click, nothing happens, and click again, the button is working, and all subsequent clicks work on the same button. Whenever the cursor is moved, then it does not work, and I need to click twice to make the button start to work.

**Comment by renkun-ken** [comment] 2020-05-30 23:59
If the WebView is in its full size in the active edtior group, the toolbar looks good:

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/4662568/83341295-61943e00-a314-11ea-9eea-0ee64a9bc897.png">

But if the WebView is dragged to other editor group, the toolbar is hardly seen any more:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/4662568/83341318-96a09080-a314-11ea-8307-14bfa19cbf90.png">

Don't have clue at the moment.

**Comment by renkun-ken** [comment] 2020-05-31 23:14
The toolbar not showing completely is because the page could be scroll up and the toolbar will show completely. With the latest commit, the click issue still exists but using the keys works quite well already.

**Comment by nx10** [comment] 2020-06-01 23:21
I investigated this today and had the same issues when embedding an iframe in the vscode webview. Howerver It works (including the issue with clicking of the toolbar), when I inline the live server html (inst/www/index.html) directly and add the following code to the page css:
```CSS
html, body {
  height: 100%;
  padding: 0;
  overflow: hidden;
}
#container {
  height: 100%;
}
```
![Code_Yli0ofSEPY](https://user-images.githubusercontent.com/33600480/83463628-df6c5c80-a46e-11ea-8863-947f508a5238.png)

I am thinking about putting the live server javascript in an extra file that you could load with a script tag.

**Comment by renkun-ken** [comment] 2020-06-01 23:52
@nx10, thanks for taking a look at this.

In vscode-R, we provide `browser` so that `utils::browseURL` opens a WebView and present the content in an iframe in it. It does not know what is in the WebView, i.e., can't distinguish httpgd live page, shiny app, R html help, etc.

Your css looks quite general purpose for embedding iframe in WebView. Do you think if it could be a problem if I put it for all so that the html of WebView triggered by `browser` looks like:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    html, body {
        height: 100%;
        padding: 0;
        overflow: hidden;
    }
    #container {
        height: 100%;
    }
  </style>
</head>
<body>
    <div id="container" style="border:0px;position:absolute;left:0px;top:0px;bottom:0px;right:0px;">
        <iframe src="${url}"; width="100%" height="100%" frameborder="0" />
    </div>
</body>
</html>
```

**Comment by nx10** [comment] 2020-06-02 12:17
I just changed the css so it is easyer to embed. The following webview iframe works for me now:

```HTML
!DOCTYPE html>
<html lang="en">
   <head>
      <style>
         html, body {
         width: 100%;
         height: 100%;
         margin: 0;
         padding: 0;
         overflow: hidden;
         }
      </style>
   </head>
   <body>
      <iframe id="my_iframe" src="http://localhost:8288/live" sandbox="allow-scripts" width="100%" height="100%" frameBorder="0"></iframe>
   </body>
</html>```

Maybe you can compare this with your implementation.

But this way you need to click twice at the exact same position to activate the toolbar actions. (Maybe focus related) and vscode shortcuts will not work anymore when the iframe has focus.
Do shiny apps not have this problem?
These issues might be with vscode itself, maybe it would be worth raising an issue there?

**Comment by renkun-ken** [comment] 2020-06-02 15:21
@nx10 Thanks for your suggested HTML for browser WebView. I test it and it works better than before with httpgd, shiny app, and R html help.

As for the click issue, the original webview HTML has the same issue, and it is the same with shiny apps too. As I remember, there are already plenty of issues talking about this.

**Comment by nx10** [comment] 2020-06-04 15:53
I will close this for now, because as it seems the remaining issues are caused by vscode not by httpgd.

**Closed by nx10** 2020-06-04 15:53 UTC

**Comment by renkun-ken** [comment] 2020-06-05 00:17
Thanks for the nice work!
